import {attribute} from './attribute';
export const attributes : attribute[] = [
    {name:'Application_CRDA',value:'' },
    {name:'appcompletedinUS',value:'' },
    {name:'ownerOtherThanPI',value:'' },
    {name:'product',value:'' },
    {name:'niprNum',value:'' },
    {name:'preAmount',value:'' },
    {name:'faceAmount',value:'' },
    {name:'illustrationPDF',value:'' },
    {name:'premiumMode',value:'' },
    {name:'lumpsum',value:'' },
    {name:'singlePremium',value:'' },
    {name:'prefix',value:'' },
    {name:'firstName',value:'' },
    {name:'middleName',value:'' },
    {name:'lastName',value:'' },
    {name:'permanentAddress',value:'' },
    {name:'dateofBirth',value:'' },
    {name:'ssn',value:'' },
    {name:'a_InforceNAppliedfor',value:'' },
    {name:'a_OffPaymtInd_PINS',value:'' },
    {name:'a_OwnSoldTransLifeInd',value:'' },
    {name:'premium_payors',value:'' },
    {name:'paymentMode',value:'' },

];